#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import numpy as np
fibonacci_list = [1,2]

def fib_less_than(k,fib_list):
    d = fib_list[-1]+fib_list[-2]
    if d<k:
        fib_list.append(d)
        fib_less_than(k,fib_list)
    return fib_list

fibs_less_than_4000000 = fib_less_than(4000000,fibonacci_list)
even_fibs_less_than_4000000 = [n for n in fibs_less_than_4000000 if n%2==0]
answer = np.sum(even_fibs_less_than_4000000)
print(answer)

#4613732